### ISSUE TITLE
Github Actions for Typescript CI (Containerized)

### ISSUE THREAD

**Issue by cyri113** [TogetherCrew/operations#1]
### Tasks

- [ ] Typescript Lint Workflow
- [ ] Typescript Build Workflow
- [ ] Typescript Test Workflow
- [ ] Typescript Publish Workflow
