### ISSUE TITLE
Create a python service template repository

### ISSUE THREAD

**Issue by cyri113** [TogetherCrew/operations#10]
## Problem

TogetherCrew is based on micro-services. As the number of micro-services will continue to grow, it is of vital importance to ensure that our services use the same pipelines, structures, and libraries (where possible).

## Solution

We will create a service template for python services. Similar to the typescript template, developers should be able to use it as a basis for any service, saving days in configuring a new service.

It should support the following commands:

### Linter
```
docker run -e RUN_LOCAL=true -e TYPESCRIPT_DEFAULT_STYLE=prettier -e VALIDATE_DOCKERFILE_HADOLINT=false -v $(pwd):/tmp/lint github/super-linter:slim-latest
```

### Tests
```
docker compose -f docker-compose.test.yml up --exit-code-from app --build
```

### Development Environment
```
docker compose -f docker-compose.dev.yml up
```

## Tasks

- [x] PST: Create Dockerfile
- [x] PST: Create .dockerignore
- [x] PST: Create docker-compose.dev.yml
- [x] PST: Create docker-compose.test.yml
- [x] PST: Create .gitignore 
- [x] PST: Github action implementation
- [x] PST: Implement RQ for background tasks
- [x] PST: Align codebase to validate super-linter
- [x] PST: Neo4j connection
- [x] PST: MongoDB connection
- [x] PST: RabbitMQ connection
- [x] PST: Redis connection
- [x] PST: Background Worker

## Documentation

- https://python-rq.org/
- https://github.com/RnDAO/tc-operation/tree/main/tc-DAOlytics-operation

## Notes

Most of the code can be ported from https://github.com/RnDAO/tc-operation/tree/main/tc-DAOlytics-operation

## Overview

The goal of the python service template is to allow us to easily create new datasource analyzers. The analysis will occur in the background using workers. To accomplish this, we will use https://python-rq.org/.

### Server

The server is responsible for the following:
- Listening for messages on RabbitMQ
- Enqueuing jobs onto a queue
- Acknowledging that a message was received

### Worker

Once a job is enqueued, it is the Workers responsibility to process the job.
- Handle the connect to datasource i.e. Neo4j, MongoDB
- Execute custom logic
- Emit messages to RabbitMQ

#### Datasources
- The developer should have then option to enable or disable a certain datasource. This can be done by simply commenting code.
- The RabbitMQ connection should be managed by (using https://github.com/TogetherCrew/broker-lib-py)

## Test cases
- Should listen to messages from RabbitMQ
- Should process job (hello world)
- Should emit messages to RabbitMQ
