### ISSUE TITLE
Create a shared analytics library

### ISSUE THREAD

**Issue by cyri113** [TogetherCrew/operations#12]
## Problem

The DAOlytics repository consists of a lot of different work, mainly research and exploratory scripts. This is mixed in with the analytics library that is used by our services. This can cause confusion and CI struggles.

## Solution

We will create a new repository that will contain only the analytics library.

It should support the following commands:

### Linter
```
docker run -e RUN_LOCAL=true -e TYPESCRIPT_DEFAULT_STYLE=prettier -e VALIDATE_DOCKERFILE_HADOLINT=false -v $(pwd):/tmp/lint github/super-linter:slim-latest
```

### Tests
```
docker compose -f docker-compose.test.yml up --exit-code-from app --build
```

### Development Environment
```
docker compose -f docker-compose.dev.yml up
```

## Tasks

- [x] SAL: Migrate the analytics library from DAOLytics
- [x] SAL: Dockerfile alignment
- [x] SAL: docker-compose.test.yml
- [x] SAL: Github action implementation
- [x] SAL: Align codebase to validate super-linter

## Prerequisite
- #13
