### ISSUE TITLE
Create a python library template repository

### ISSUE THREAD

**Issue by cyri113** [TogetherCrew/operations#13]
## Problem

TogetherCrew uses purpose built libraries. As the number of libraries will continue to grow, it is of vital importance to ensure that our libraries use the same pipelines, structures, and libraries (where possible).

## Solution

We will create a library template for python libraries. Developers should be able to use it as a basis for any service, saving days in configuring a new library.

It should support the following commands:

### Linter
```
docker run -e RUN_LOCAL=true -e TYPESCRIPT_DEFAULT_STYLE=prettier -e VALIDATE_DOCKERFILE_HADOLINT=false -v $(pwd):/tmp/lint github/super-linter:slim-latest
```

### Tests
```
docker compose -f docker-compose.test.yml up --exit-code-from app --build
```

### Development Environment
```
docker compose -f docker-compose.dev.yml up
```

## Tasks

- [ ] PLT: Create Dockerfile
- [ ] PLT: Create docker-compose.dev.yml
- [ ] PLT: Create docker-compose.test.yml
- [ ] PLT: Github action implementation
- [ ] PLT: Implement core structure
- [ ] PLT: Align codebase to validate super-linter
