### ISSUE TITLE
Create a discord-analyser repository

### ISSUE THREAD

**Issue by cyri113** [TogetherCrew/operations#15]
## Problem

The code for running the discord analyser is currently in a folder on /tc-operations. This is bad practice as they solve very different problems.

## Solution

Move the discord analyser to a separate repository.

It should support the following commands:

### Linter
```
docker run -e RUN_LOCAL=true -e TYPESCRIPT_DEFAULT_STYLE=prettier -e VALIDATE_DOCKERFILE_HADOLINT=false -v $(pwd):/tmp/lint github/super-linter:slim-latest
```

### Tests
```
docker compose -f docker-compose.test.yml up --exit-code-from app --build
```

### Development Environment
```
docker compose -f docker-compose.dev.yml up
```

## Tasks
- [ ] DA: Move to separate repository /discord-analyser
- [ ] DA: Github action implementation
- [ ] DA: Align codebase to validate super-linter

## Prerequisite
- #10
