### ISSUE TITLE
Github Actions for Python CI (Containerized)

### ISSUE THREAD

**Issue by cyri113** [TogetherCrew/operations#2]
### Tasks

- [ ] Define a Python Lint workflow
- [ ] Define a Python Build workflow
- [ ] Define a Python Test workflow
- [ ] Define a Python Push workflow
- [ ] Define a Python Release workflow
