### ISSUE TITLE
Github Action for Staging CD

### ISSUE THREAD

**Issue by cyri113** [TogetherCrew/operations#3]
### Tasks

- [ ] Define a docker-compose file for the orchestration of a multiple-container docker application
- [ ] Define a Github Action that deploys the docker-compose app file to an EC2 instance.
- [ ] Define a Github Action that shuts down the EC2 instance (manual)
- [ ] Define a Github Action that terminates the EC2 instance (manual)

### Open Questions

- When should this be triggered?
- How will it be triggered? i.e. who will call it?
- Which images should be included?
