### ISSUE TITLE
CI: Core analyzer extraction from daolytics

### ISSUE THREAD

**Issue by amindadgar** [TogetherCrew/operations#58]
As we're moving all repositories from RnDAO organization into TogetherCrew, we need to extract the core analyzer from the DAOlytics repository so we could have a better vision on our analyzer scripts and we could use it in different modules. 

```[tasklist]
### Tasks
- [x] Extract the `assess_engagement.py` from DAOlytics into a repository with name `core-analyzer`
- [x] Extract the related tests for the script and add them to the new repository
- [x] Align codebase with super-linter
- [x] Add docker-compose.test.yml
```
